name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: Runner version
        type: string
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest # dz-runner-set
    # container: docker.io/docker:latest
    # services:
    #   dind:
    #     image: docker.io/docker:dind
    #     options: "--entrypoint dockerd"
    #     ports:
    #        - 2375:2375
    # env:
    #   DOCKER_HOST: "tcp://localhost:2375"
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.runner_version }},ghcr.io/${{ github.repository }}:latest
          build-args: RUNNER_VERSION=${{ inputs.runner_version }}
