name: Docker Image CI Zuhair
on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: Runner version
        type: string
        required: true
jobs:
  docker:
    runs-on: dz-runner-set-zuhair
    container: docker.io/docker:20.10
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          docker version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.runner_version }},ghcr.io/${{ github.repository }}:latest
          build-args: RUNNER_VERSION=${{ inputs.runner_version }}
